graph TB
    AWR[ApplyWalRecord<br/>xlogrecovery.c:1908] -->|GetRmgr rmid| TBL[RmgrTable in rmgr.c<br/>indexed by rmid]
    TBL -->|0 RM_XLOG_ID| XL[xlog_redo<br/>xlog.c:8251<br/>checkpoints, FPI, NEXTOID,<br/>PARAMETER_CHANGE, RESTORE_POINT]
    TBL -->|1 RM_XACT_ID| XA[xact_redo<br/>xact.c:6301<br/>COMMIT, ABORT, PREPARE,<br/>COMMIT/ABORT_PREPARED,<br/>ASSIGNMENT, INVALIDATIONS]
    TBL -->|2 RM_SMGR_ID| SM[smgr_redo<br/>storage.c:965<br/>SMGR_CREATE, SMGR_TRUNCATE]
    TBL -->|3 RM_CLOG_ID| CL[clog_redo<br/>clog.c:1107<br/>ZEROPAGE, TRUNCATE]
    TBL -->|4 RM_DBASE_ID| DB[dbase_redo<br/>dbcommands.c:3270<br/>CREATE_FILE_COPY,<br/>CREATE_WAL_LOG, DROP]
    TBL -->|5 RM_TBLSPC_ID| TS[tblspc_redo<br/>tablespace.c:1511<br/>CREATE, DROP]
    TBL -->|6 RM_MULTIXACT_ID| MX[multixact_redo<br/>multixact.c:3386<br/>ZERO_OFF/MEM_PAGE,<br/>CREATE_ID, TRUNCATE_ID]
    TBL -->|7 RM_RELMAP_ID| RM[relmap_redo<br/>relmapper.c:1096<br/>RELMAP_UPDATE]
    TBL -->|8 RM_STANDBY_ID| SB[standby_redo<br/>standby.c:1159<br/>STANDBY_LOCK,<br/>RUNNING_XACTS,<br/>INVALIDATIONS]
    TBL -->|9 RM_HEAP2_ID| H2[heap2_redo<br/>heapam.c:10384<br/>PRUNE_*, VISIBLE,<br/>MULTI_INSERT, LOCK_UPDATED,<br/>NEW_CID, REWRITE]
    TBL -->|10 RM_HEAP_ID| HE[heap_redo<br/>heapam.c:10338<br/>INSERT, DELETE, UPDATE,<br/>HOT_UPDATE, CONFIRM, LOCK,<br/>INPLACE, TRUNCATE]
    TBL -->|11 RM_BTREE_ID| BT[btree_redo<br/>nbtxlog.c:1014<br/>+ rm_startup/cleanup<br/>INSERT, SPLIT, DELETE,<br/>VACUUM, REUSE_PAGE]
    TBL -->|12 RM_HASH_ID| HA[hash_redo<br/>hash_xlog.c:1067<br/>INSERT, SPLIT, DELETE,<br/>VACUUM_ONE_PAGE]
    TBL -->|13 RM_GIN_ID| GI[gin_redo<br/>ginxlog.c:726<br/>+ rm_startup/cleanup]
    TBL -->|14 RM_GIST_ID| GS[gist_redo<br/>gistxlog.c:397<br/>+ rm_startup/cleanup<br/>PAGE_REUSE conflict]
    TBL -->|15 RM_SEQ_ID| SQ[seq_redo<br/>sequence.c:1834<br/>SEQ_LOG]
    TBL -->|16 RM_SPGIST_ID| SP[spg_redo<br/>spgxlog.c:935<br/>+ rm_startup/cleanup<br/>VACUUM_REDIRECT conflict]
    TBL -->|17 RM_BRIN_ID| BR[brin_redo<br/>brin_xlog.c:309]
    TBL -->|18 RM_COMMIT_TS_ID| CT[commit_ts_redo<br/>commit_ts.c:1023<br/>ZEROPAGE, TRUNCATE]
    TBL -->|19 RM_REPLORIGIN_ID| RO[replorigin_redo<br/>origin.c:827<br/>SET, DROP]
    TBL -->|20 RM_GENERIC_ID| GE[generic_redo<br/>generic_xlog.c:478<br/>page-deltas]
    TBL -->|21 RM_LOGICALMSG_ID| LM[logicalmsg_redo<br/>message.c:87<br/>no-op]
    TBL -.->|128..255| CR[Custom rmgrs<br/>RegisterCustomRmgr<br/>extension surface]
